# ##### SUCCESS #####
CODE_SUCCESS_ADD_FLAG = "SUCCESS_ADD_FLAG"
CODE_SUCCESS_GET_ALL_FLAGS = "SUCCESS_GET_ALL_FLAGS"
CODE_SUCCESS_DELETE_FLAG = "SUCCESS_DELETE_FLAG"
CODE_SUCCESS_ADD_MODE = "SUCCESS_ADD_MODE"
CODE_SUCCESS_GET_ALL_MODES = "SUCCESS_GET_ALL_MODES"
CODE_SUCCESS_GET_MODE = "SUCCESS_GET_MODE"
CODE_SUCCESS_GET_TOP_MODE = "SUCCESS_GET_TOP_MODE"
CODE_SUCCESS_DELETE_MODE = "SUCCESS_DELETE_MODE"
CODE_SUCCESS_ADD_USER = "SUCCESS_ADD_USER"
CODE_SUCCESS_UPDATE_USER = "SUCCESS_UPDATE_USER"
CODE_SUCCESS_GET_ALL_USERS = "SUCCESS_GET_ALL_USERS"
CODE_SUCCESS_GET_GLOBAL_TOP_USER = "SUCCESS_GET_GLOBAL_TOP_USER"
CODE_SUCCESS_DELETE_USER = "SUCCESS_DELETE_USER"

# ##### ERROR #####
CODE_ERROR_INTERNAL_SERVER = "ERROR_INTERNAL_SERVER"
CODE_ERROR_PYDANTIC = "ERROR_PYDANTIC"
CODE_ERROR_DATABASE = "ERROR_DATABASE"
CODE_ERROR_GENERIC = "ERROR_GENERIC"
CODE_ERROR_AUTHENTICATION = "ERROR_AUTHENTICATION"

# ##### NOT #####

# ##### NOT_VALID #####
CODE_NOT_VALID_INTEGER = "NOT_VALID_INTEGER"

# ##### NOT_EXISTS #####

# ##### ALREADY_EXISTS #####
CODE_ALREADY_EXISTS_FLAG = "ALREADY_EXISTS_FLAG"
CODE_ALREADY_EXISTS_MODE = "ALREADY_EXISTS_MODE"
CODE_ALREADY_EXISTS_USER = "ALREADY_EXISTS_USER"

# ##### NOT_FOUND #####
CODE_NOT_FOUND_FLAG = "NOT_FOUND_FLAG"
CODE_NOT_FOUND_MODE = "NOT_FOUND_MODE"
CODE_NOT_FOUND_USER = "NOT_FOUND_USER"
