services:
  flag-oracle-app:
    build:
      context: ./flag-oracle-app
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./flag-oracle-app/.env
    volumes:
      - ./flag-oracle-app:/home/app
      - /home/app/node_modules
    depends_on:
      - flag-oracle-api
    ports:
      - "3000:3000"
    networks:
      - flag-oracle-net
    stdin_open: true
    tty: true

  flag-oracle-api:
    build:
      context: ./flag-oracle-api
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./flag-oracle-api/.env
    volumes:
      - ./flag-oracle-api:/home/app
    depends_on:
      - flag-oracle-db
    ports:
      - "5050:5050"
    networks:
      - flag-oracle-net

  flag-oracle-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: flags
    volumes:
      - db-data:/data/db
    networks:
      - flag-oracle-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret123@flag-oracle-db:27017/flags?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - flag-oracle-db
    networks:
      - flag-oracle-net

volumes:
  db-data:
    driver: local

networks:
  flag-oracle-net:
    driver: bridge
