services:
  flag-oracle-app:
    build:
      context: ./flag-oracle-app
      dockerfile: Dockerfile.production
    restart: always
    env_file:
      - ./flag-oracle-app/.env
    depends_on:
      - flag-oracle-api
    ports:
      - "80:80"
    networks:
      - flag-oracle-net

  flag-oracle-api:
    build:
      context: ./flag-oracle-api
      dockerfile: Dockerfile.production
    restart: always
    env_file:
      - ./flag-oracle-api/.env
    depends_on:
      - flag-oracle-db
    ports:
      - "5050:5050"
    networks:
      - flag-oracle-net

  flag-oracle-db:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: flags
    volumes:
      - db-data:/data/db
    networks:
      - flag-oracle-net

volumes:
  db-data:
    driver: local

networks:
  flag-oracle-net:
    driver: bridge